"""Phase 2 (סעיף ב): the 5 AI-generated, RESTRICTED-vocabulary texts.

How these were produced
-----------------------
The texts in data/generated/ were generated by Claude (the same model family the
assignment names as the example LLM) using the exact prompt saved in
data/generation_prompt.txt. The graded constraint is that the prompt asks the
model to use as LIMITED / RESTRICTED a vocabulary as possible (אוצר מילים מצומצם);
the generated texts deliberately use simple, repeated, jargon-free words, which
contrasts sharply with the rich/technical vocabulary of the original Wikipedia
articles. That contrast is what makes the later embedding comparison interesting.

This script:
  * validates that all 5 generated files exist and meet the >=300-word minimum;
  * if ANTHROPIC_API_KEY is set and --regenerate is passed, re-creates the texts
    through the API using the saved prompt (so the pipeline is reproducible).

Run:  python -m src.generate_texts            # validate only
      python -m src.generate_texts --regenerate  # call the API (needs key)
"""
from __future__ import annotations

import os
import sys

from src.config import GEN_PROMPT_FILE, GENERATED_DIR, MIN_WORDS, TOPICS
from src.text_utils import word_count


def _prompt_for(topic_title: str) -> str:
    template = GEN_PROMPT_FILE.read_text(encoding="utf-8")
    # The prompt file documents the template with a {TOPIC} placeholder in prose;
    # fill it for an actual API call.
    return template.replace("{TOPIC}", topic_title)


def regenerate_via_api() -> int:
    try:
        import anthropic  # noqa: PLC0415
    except ImportError:
        print("!! `anthropic` not installed; cannot regenerate. Keeping saved texts.")
        return 1
    if not os.environ.get("ANTHROPIC_API_KEY"):
        print("!! ANTHROPIC_API_KEY not set; cannot regenerate. Keeping saved texts.")
        return 1
    client = anthropic.Anthropic()
    for i, (slug, title, _domain) in enumerate(TOPICS, start=1):
        msg = client.messages.create(
            model="claude-opus-4-8",
            max_tokens=1200,
            messages=[{"role": "user", "content": _prompt_for(title)}],
        )
        text = msg.content[0].text.strip()
        (GENERATED_DIR / f"wiki_gen_{i:02d}_{slug}.txt").write_text(text, "utf-8")
        print(f"  regenerated wiki_gen_{i:02d}_{slug}.txt ({word_count(text)} words)")
    return 0


def validate() -> int:
    ok = True
    for i, (slug, _title, _domain) in enumerate(TOPICS, start=1):
        path = GENERATED_DIR / f"wiki_gen_{i:02d}_{slug}.txt"
        if not path.exists():
            print(f"  !! MISSING {path.name}")
            ok = False
            continue
        wc = word_count(path.read_text(encoding="utf-8"))
        flag = "OK " if wc >= MIN_WORDS else "!! "
        if wc < MIN_WORDS:
            ok = False
        print(f"  {flag}{path.name}  ({wc} words)")
    return 0 if ok else 1


def main(argv: list[str]) -> int:
    if "--regenerate" in argv:
        regenerate_via_api()
    print("Validating generated texts (>=%d words):" % MIN_WORDS)
    return validate()


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
